### ISSUE TITLE
Add OJS/OMD Preview WebviewPanelSerializer

### ISSUE THREAD

**Issue by RandomFractals** [GordonSmith/vscode-ojs#10]
Gordon,

I added save as .ojs & .omd options to my JS notebook inspector:

https://github.com/RandomFractals/js-notebook-inspector/issues/54

Everything looks good, except OJS/OMD Preview webview is not restored on vscode restart.

before:

![js-notebook-inspector-omd-save](https://user-images.githubusercontent.com/656833/97086205-7e911c80-15e7-11eb-973c-fe3f09875a49.png)

that OMD Preview panel is gone after that vscode instance restart:

![ojs-preview-blank-restore](https://user-images.githubusercontent.com/656833/97086220-8a7cde80-15e7-11eb-8a1f-96cc9bd566f7.png)

Expected to see same thing as in pic 1.

It would be nice if you could add WebviewPanelSerializer for those custom .ojs/.omd panels.

See my notebook.view.ts for an example of implementing that api:

https://github.com/RandomFractals/js-notebook-inspector/blob/master/src/views/notebook.view.ts

**Comment by RandomFractals** [comment]
btw, I noticed you removed OJS: prefix from your command names. I kind of liked it. I believe most good vscode extensions use ext. prefix in command names for easy command search via Command Palette.

**Comment by GordonSmith** [comment]
I replaced it with "category" which should prefix it in the command list...

**Comment by RandomFractals** [comment]
oh. I missed that. cool!
