### ISSUE TITLE
Narrow notebook content width in exported html webpage view

### ISSUE THREAD

**Issue by RandomFractals** [GordonSmith/vscode-ojs#26]
Hi Gordon,

I tried your new html export option. I like the styles you added for objects and arrays display.

However, I got very narrow webpage view when opening it in FireFox:

![image](https://user-images.githubusercontent.com/656833/123126088-b8cceb00-d40e-11eb-94d5-8a05d4fabc9c.png)

and Chrome: 

![image](https://user-images.githubusercontent.com/656833/123126315-e74ac600-d40e-11eb-86a6-4504bef35182.png)

I will try other notebooks.

**Comment by RandomFractals** [comment]
changing `#placeholder` max-width css property to 1080px fixes it :slightly_smiling_face: 

```
    #placeholder {
        position: absolute;
        left: 8px;
        top: 8px;
        right: 8px;
        bottom: 8px;
        max-width: 1080px;
    }
```

**Comment by RandomFractals** [comment]
actually, I removed that `max-width` css setting completely to see a larger map on a wider screen:

![image](https://user-images.githubusercontent.com/656833/123128045-6d1b4100-d410-11eb-8e1f-dbcdd868c600.png)

Not sure if you want to do the same for all html exports.

Thanks!

**Comment by GordonSmith** [comment]
FYI those styles simply matched the Observable web site at the time (but not centered) - as you have probably worked out now, the html export is really just a demo, once you see that the "widget" is simply loading the ojs text or omd text then you can create your own web site drived from your own DB server etc.

BTW the export isn't new, its been there from day one pretty much...

**Comment by GordonSmith** [comment]
Further - I had raised an issue with Mike Bostock re the default width on the website being too narrow and his response was that its harder to read the text when its gets beyond a certain number of words per line...

**Comment by RandomFractals** [comment]
that's fine. I would just make the change I suggested in your html exports. up to you.

**Comment by GordonSmith** [comment]
If you want to make the width configurable within the @hpcc-js/observable-md "widget", please open a ticket here:  https://github.com/hpcc-systems/Visualization/issues

**Comment by RandomFractals** [comment]
I am not familiar with what you refer to as widgets and that repo. I know you use it for this extension. Maybe just clip this one there with more info if needed.

**Comment by GordonSmith** [comment]
Sure.  FWIW the Widget in question is what renders the raw text in a web page - normally the widgets adjust to the hosting DIV width and height.
