### ISSUE TITLE
Provide notebook UI using VS Code Notebook API

### ISSUE THREAD

**Issue by gnestor** [GordonSmith/vscode-ojs#32]
I've been wanting to play with the [VS Code Notebook API](https://code.visualstudio.com/api/extension-guides/notebook) for a while but I haven't found the time. This extension already has the core functionality for integrating the Observable runtime and parser with the VS Code Notebook API. It would be great if we could work in a notebook like on observablehq.com and have access to VS Code's features (formatters, language servers, and extensions in general). If you haven't tried VS Code's notebook UI, you can try opening a Jupyter notebook file (.ipynb) and it should just work if you have the Python extension installed. I would love to be able to check notebooks into source control, refactor variable names across all of my Observable notebooks, and eventually write Observable notebooks in Node.js or Deno. I will definitely help with this if someone can get the ball rolling 👍

**Comment by GordonSmith** [comment]
That was my original plan - but each time I use the notebook style editor over the simpler OMD file format, I feel it slows me down.
I do agree being able mix languages into an Observable notebook would be cool though!  Its on the cards...
