### ISSUE TITLE
Thank you for making this.

### ISSUE THREAD

**Issue by HansUXdev** [GordonSmith/vscode-ojs#5]
Now I need to learn how to use Observable JS 😓 but its really cool.

**Comment by RandomFractals** [comment]
this collection is a good place to start: https://observablehq.com/collection/@observablehq/techniques

**Comment by StephenAtKinetiq** [comment]
> @observablehq/techniques

Is now defunct as a learning page.

"Sorry, but we can’t find that page right now."
