### ISSUE TITLE
Repeated Code Execution Issue in OJS - "RuntimeError: x is defined more than once"

### ISSUE THREAD

**Issue by jersonlatorre** [GordonSmith/vscode-ojs#59]
Encountering problem with repeated code execution. Initially, running code block with "x = 10" works, but running it again leads to "RuntimeError: x is defined more than once" error.

**Comment by GordonSmith** [comment]
What file type are you using?

**Comment by jersonlatorre** [comment]
im using .ojsnb

**Comment by GordonSmith** [comment]
Seems to happen with a new file, once you save and reopen it works as expected (is that what your seeing)?

**Comment by jersonlatorre** [comment]
Yes, that's exactly what happens to me. Should I handle it that way? Or is there a way to fix it?
