### ISSUE TITLE
Fetch error 

### ISSUE THREAD

**Issue by yugin-pro** [GordonSmith/vscode-ojs#64]
Hi there!
Trying to analyse several website content using ObservableHQ Notebook running on my laptop in VS code Windows 10 OS.
here is the code line in a cell which is perfectly working when i download something like https:site/file.json
```
{
    return fetch('https://google.com/').catch(e => e)
}
```
but when I want to parse html It return the error:

> TypeError: Failed to fetch at eval (eval at createFunction (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/yugin/.vscode/extensions/gordonsmith.observable-js-0.4.37/dist/ojsRenderer.js:6659:12), <anonymous>:4:12) at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/yugin/.vscode/extensions/gordonsmith.observable-js-0.4.37/dist/ojsRenderer.js:11499:61 at new Promise (<anonymous>) at variable_compute (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/yugin/.vscode/extensions/gordonsmith.observable-js-0.4.37/dist/ojsRenderer.js:11499:9) at Runtime.runtime_computeNow (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/yugin/.vscode/extensions/gordonsmith.observable-js-0.4.37/dist/ojsRenderer.js:11410:7) at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/yugin/.vscode/extensions/gordonsmith.observable-js-0.4.37/dist/ojsRenderer.js:11347:74

**Comment by GordonSmith** [comment]
Does that code work in an online ObservableHQ notebook?

**Comment by yugin-pro** [comment]
https://observablehq.com/d/999d3a227480b7c0
I've got this
TypeError: Failed to fetch
    at eval (observablehq-5:4:10)
    at https://static.observableusercontent.com/next/worker-d1e48427.js:2:69862
    at new Promise (<anonymous>)
    at ea (https://static.observableusercontent.com/next/worker-d1e48427.js:2:69830)
    at Vr.value (https://static.observableusercontent.com/next/worker-d1e48427.js:2:73824)
    at https://static.observableusercontent.com/next/worker-d1e48427.js:2:72908

**Comment by GordonSmith** [comment]
In which case I would consider this to not be an issue in the notebook as such, but rather in the Observable Runtime (or it may be the runtime working as expected)...
